### ISSUE TITLE
libssl.so.1.0.0 deprecated

### ISSUE THREAD

**Issue by mgarces** [mbtproject/mbt#126]
When trying to "dockerize" mbt, I'm having troubles using it, because it was built to the deprecated libssl.so.1.0.0; can you please release the binary with updated support? In Debian is possible to use a custom install, but in CentOS I'm having issues going around this.

- mbt version: 0.23
- os: CentOS 7.7 or Debian 10 (inside a container)
- arch: x86_64

**Comment by buddyspike** [comment]
@mgarces Thanks for reporting this. 
We could not keep up with libgit2 for a while due to a bug in libgit2 that got fixed recently. 
Could you please check if latest nightly build is working?
https://bintray.com/buddyspike/bin/mbt_dev_linux_x86_64/dev-e1ffe970#files/mbt_dev_linux_x86_64/dev-e1ffe970/dev-e1ffe970

**Comment by mgarces** [comment]
will give it a spin

**Comment by mgarces** [comment]
It seem that it's still trying to get older libs:
`mbt: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by buddyspike** [comment]
> It seem that it's still trying to get older libs:
> `mbt: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

Thanks, I will take a look.

**Comment by buddyspike** [comment]
@mgarces Apologies for the lag in my response on this one. I believe that this is happening because build servers have libssl 1.0. We need to produce a new artefact targetting newer version of libssl. Until this is done, you should be able to build it from source.

**Comment by buddyspike** [comment]
@mgarces We have recently upgraded our build infrastructure. Latest release should be linked with fresher libssl. you should be able to use the latest build from https://github.com/mbtproject/mbt/releases/tag/v0.24

Please re-open this issue if you are having further issues.

**Comment by sirianni** [comment]
I am seeing the same issue with `v0.24`
```
$ curl -L -o mbt 'https://bintray.com/buddyspike/bin/download_file?file_path=mbt_linux_x86_64%2F0.23.0%2F0.23.0%2Fmbt_linux_x86_64'

$ chmod +x mbt

$ ldd ./mbt
	linux-vdso.so.1 (0x00007fff321d5000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fb849433000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb849411000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fb8493f7000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb849230000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb84947a000)
```

**Comment by sirianni** [comment]
Actually looks like I was using `v0.23`.  So I think the problem is that the links on the README badges need to be updated (or removed).  Seems like the project is now using GitHub releases instead of bintray.
