### ISSUE TITLE
Can't build mbt in alpine based container

### ISSUE THREAD

**Issue by geoffbp** [mbtproject/mbt#135]
**Do you want to report a bug?**

I want to report a bug I've encountered with building mbt in a docker container.

**Which mbt command are you having troubles with?**

We are trying to build mbt inside a container running alpine. This worked until recently, sorry I don't have a date for when the container last built sucessfully

**What's the current behaviour?**

I'm unable to build mbt with the vendor provided libgit2

Dockerfile:
```
FROM golang:alpine as build

RUN apk update
RUN apk add --no-cache \
    pkgconf \
    libssh2-dev \
    musl-dev \
    cmake \
    make \
    perl-utils \
    gcc \
    bash \
    http-parser-dev \
    git

RUN go get github.com/mbtproject/mbt && \
    cd $GOPATH/src/github.com/mbtproject/mbt && \
    make build && \
    make install

RUN mkdir /src
WORKDIR /src

ENTRYPOINT ["/go/bin/mbt"]
```

Error:
```
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM golang:alpine as build
 ---> cda74ca0cbba
Step 2/7 : RUN apk update
 ---> Using cache
 ---> 998a19b63e89
Step 3/7 : RUN apk add --no-cache     pkgconf     libssh2-dev     musl-dev     cmake     make     perl-utils     gcc     bash     http-parser-dev     git
 ---> Using cache
 ---> e283f1e4ad6e
Step 4/7 : RUN go get github.com/mbtproject/mbt &&     cd $GOPATH/src/github.com/mbtproject/mbt &&     make build &&     make install
 ---> Running in bbed64a316f4
# pkg-config --cflags  -- libgit2
Package libgit2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgit2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libgit2', required by 'virtual:world', not found
pkg-config: exit status 1
The command '/bin/sh -c go get github.com/mbtproject/mbt &&     cd $GOPATH/src/github.com/mbtproject/mbt &&     make build &&     make install' returned a non-zero code: 2
```

**What's the expected behaviour?**

Previously this dockerfile was able to create a working mbt docker image. FWIW I wasn't the developer of the dockerfile, from what I've read the make build isn't required if we're using make install.

**Environment**

- mbt version: We're using `go get github.com/mbtproject/mbt` so latest I guess?
- os: alpine
- arch: x86

**Comment by buddyspike** [comment]
Thanks for reporting this issue. It looks like `go get` is attempting to run the build without using `build.sh`. I have to look into how to stop this when someone downloads the package using `go get`. 

For the time being, you could try replacing `go get github.com/mbtproject/mbt` to `git clone https://github.com/mbtproject/mbt $GOPATH/src/github.com/mbtproject/mbt`. It should do the trick.

**Comment by buddyspike** [comment]
You can use `go get` with option `-d` which will stop the `go install` command during `get`. 

```
go get -d github.com/mbtproject/mbt
```

`make install` should not be used in this context. You could copy the output of `make build` and adjust entry point. Following `Dockerfile` is probably the one I would recommend.

```
FROM golang:alpine as build

RUN apk update
RUN apk add --no-cache \
    pkgconf \
    libssh2-dev \
    musl-dev \
    cmake \
    make \
    perl-utils \
    gcc \
    bash \
    http-parser-dev \
    git

RUN go get -d github.com/mbtproject/mbt && \
    cd $GOPATH/src/github.com/mbtproject/mbt && \
    make build && \ 
    cp "build/mbt_dev_$(uname -s | awk '{print tolower($0)}')_$(uname -m)" /usr/local/bin/mbt

RUN mkdir /src
WORKDIR /src

ENTRYPOINT ["mbt"]
```

**Comment by geoffbp** [comment]
Thanks @buddyspike, I will give your suggestions a try soon and let you know how it goes

**Comment by geoffbp** [comment]
👍  works perfectly. thanks!

**Comment by geoffbp** [comment]
FWIW, if anyone wanted to build a mbt container from a binary pull the dockerfile below worked.

```
FROM debian:jessie

RUN apt-get update
RUN apt-get -y install git curl bash libssl1.0 libssl-dev

RUN mkdir -p /go/bin
RUN curl -L -o /go/bin/mbt https://dl.bintray.com/buddyspike/bin/mbt_linux_x86_64/0.23.0/0.23.0/mbt_linux_x86_64
RUN chmod +x /go/bin/mbt

RUN mkdir /src
WORKDIR /src

ENTRYPOINT ["/go/bin/mbt"]
```

**Comment by pratikbalar** [comment]
i got working `mbt` in alpine by installing glibc :see_no_evil:
Thanks to [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc)
```bash
apk add curl &
curl -L -o /usr/local/bin/mbt https://github.com/mbtproject/mbt/releases/download/v0.24/mbt_linux_x86_64
chmod +x /usr/local/bin/mbt
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.33-r0/glibc-2.33-r0.apk
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.33-r0/glibc-bin-2.33-r0.apk
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.33-r0/glibc-i18n-2.33-r0.apk
apk add glibc-2.33-r0.apk
apk add glibc-bin-2.33-r0.apk glibc-i18n-2.33-r0.apk
/usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
mbt
```
