### ISSUE TITLE
Build local changes without committing

### ISSUE THREAD

**Issue by buddyspike** [mbtproject/mbt#14]
At the moment all `mbt` commands operate on changes that are committed to the repository. 

While developing, it could be quite handy to be able to build changes in your workspace, therefore it would be good to have this as a supported workflow as follows.

```
mbt build local
```
Discovers the modules based on the local workspace state and builds the ones that are affected by current (uncommitted) changes

```
mbt apply local --to <path to template>
```
Applies the local repository state to the specified path in working directory

```
mbt describe local
```
Displays all discoverable modules in topological order

**Comment by wenisman** [comment]
this should be resolved by feature #16
