### ISSUE TITLE
Diff build is not working as expected in CI

### ISSUE THREAD

**Issue by pratikbin** [mbtproject/mbt#141]
Looks like diff build is not working in my CI, I bet it was working a few weeks ago that's why I setup in my CI and now it's not I know it's so weird.
> - Is it because I compiled it in alpine for alpine? <https://github.com/mbtproject/mbt/pull/140>

i mainly use this for creating Docker images. my repo setup is like this
```log
└── myapplication
    ├── backend
    │   ├── .mbt.yml
    │   ├── Dockerfile
    │   └── stuff.go
    ├── build.sh (for building docker images)
    ├── ci.yaml
    └── frontend
        ├── .mbt.yml
        ├── Dockerfile
        └── stuff.js
```

`.mbt.yaml`
```yaml
name: myapplication-backend/frontend
build:
  darwin:
    cmd: ../build.sh
  linux:
    cmd: ../build.sh
```

when I check `mbt describe branch ${CIRCLECI_BRANCH}` it shows me correct changes like

before commit 
```log
Name                PATH    VERSION
myapplication-backend     app     cac52217a2ff7500d4faaf10fc1c81d829148354
myapplication-frontend    web     0cec9b1a17c05bf71612870f74e8e8c7cf7f24e2
```

after commit
```log
Name                PATH    VERSION
myapplication-backend     app     cac52217a2ff7500d4faaf10fc1c81d829148354
myapplication-frontend    web     9dd744d251a08fbebdb8f831905f56015137447f
```

but when I `mbt build branch ${CIRCLECI_BRANCH}` it's building both targets in both scenarios instead of building just frontend

i setup build command in CI liket this `mbt build branch ${CIRCLECI_BRANCH}`

**Comment by pratikbalar** [comment]
not that i really thought it's pointless
