### ISSUE TITLE
[enhancement] Ability to run custom functions

### ISSUE THREAD

**Issue by dustyhorizon** [mbtproject/mbt#38]
It would be great if mbt could run custom functions as defined in .mbt.yml, similar to yarn/npm run x where x is defined in package.json

**Comment by buddyspike** [comment]
This is a great idea. In our environment, we want to run some automated UI tests for modules effected by a commit (outside the build process). Having something like:
`mbt run <command> --for <commit|branch>` would be really handy.
So, definitely, going to the next to-do pile.

Thank you!

**Comment by buddyspike** [comment]
For the time being you could parse the output of `mbt describe xxx --json` in your scripts to apply custom logic.

**Comment by buddyspike** [comment]
@dustyhorizon This change is now available in latest dev build. Please let us know what you think. Thanks!
