### ISSUE TITLE
`mbt build branch` doesn't honor dependencies

### ISSUE THREAD

**Issue by pznamensky** [mbtproject/mbt#9]
Hi,
We've noticed that when we're building project via:
`mbt build branch master --in .`
mbt builds modules one by one in alphabet order:
```
~ $ mbt build branch master --in . | grep INFO
INFO[0000] BUILD module-a in module-a for 4d7de1733c7b2b231e50ca197de714a6385916ed
INFO[0000] BUILD module-b in module-b for 6908e3e689b72ffd64070c281997c0c9d60271b5
INFO[0000] BUILD module-c in module-c for 68af707b99e9864f71b1f61be870307e48d0f1c3
INFO[0000] BUILD module-d in module-d for 024c073bf4e6efe31aed8281b48a998753d3214c
```
Nevertheless `build diff --from <sha> --to <sha> --in .` works as expected: modules building with honoring dependencies info:
```
~ $ mbt build diff --from <sha> --to <sha> --in . | grep INFO
INFO[0000] BUILD module-a in module-a for 4d7de1733c7b2b231e50ca197de714a6385916ed
INFO[0000] BUILD module-d in module-d for 024c073bf4e6efe31aed8281b48a998753d3214c
INFO[0000] BUILD module-c in module-c for 68af707b99e9864f71b1f61be870307e48d0f1c3
INFO[0000] BUILD module-b in module-b for 6908e3e689b72ffd64070c281997c0c9d60271b5
```

**Comment by buddyspike** [comment]
Thanks for reporting this. I'm working on a fix for this.

**Comment by pznamensky** [comment]
Thank you!

**Comment by buddyspike** [comment]
My pleasure. During very early days of mbt, it used to sort the modules by the path (for display purposes). Eventually, build command started using the same thing but, without removing the sort ;-). Thank you for reporting. New binaries should appear soon in bintray. Let me know how you go.

**Comment by pznamensky** [comment]
Works fine for us.
Thanks.
